export const faPhotos: Record<string, { title: string }> = {
  "Morning desk setup": { title: "میز کار صبحگاهی در تهران" },
  "City lights at dusk": { title: "چراغ‌های برج میلاد در غروب" },
  "Coastline trail": { title: "مسیر ساحلی بندر انزلی" },
  "Studio whiteboard": { title: "وایت‌برد استودیوی کار تیمی" },
  "Coffee and laptop": { title: "قهوه و لپ‌تاپ در کافه ولیعصر" },
  "Library aisle": { title: "راهرو کتابخانه ملی ایران" },
  "Mountain ridge": { title: "خط‌الراس توچال" },
  "Neon alley": { title: "کوچه نئون خیابان جمهوری" },
  "Quiet harbor": { title: "بندر آرام بوشهر" },
  "Rooftop plants": { title: "گیاهان پشت‌بام خانه یزدی" },
  "Keyboard close-up": { title: "نمای نزدیک کیبورد مکانیکال" },
  "Rain on glass": { title: "باران روی شیشه پنجره رشت" },
  "Sunset plaza": { title: "غروب در تخت جمشید" },
  "Forest path": { title: "مسیر جنگلی ماسال" },
  "Bridge cables": { title: "پل خواجو در اصفهان" },
  "Market stall": { title: "غرفه بازار وکیل" },
  "Desert road": { title: "جاده کویر مصر" },
  "Snowy street": { title: "خیابان برفی تبریز" },
  "Airport window": { title: "پنجره فرودگاه امام خمینی" },
  "Garden bench": { title: "نیمکت باغ ارم شیراز" },
  "Train platform": { title: "سکوی ایستگاه راه‌آهن تهران" },
  "Museum hall": { title: "سالن موزه ایران باستان" },
  "Park fountain": { title: "آبنمای پارک ملت" },
  "Skyline fog": { title: "مه روی افق البرز و تهران" },
};
