export const faTodos: Record<string, { title: string }> = {
  "Ship Posts docs page": { title: "انتشار صفحه مستندات پست‌ها" },
  "Wire OpenAPI for Comments": { title: "وصل کردن OpenAPI برای کامنت‌ها" },
  "Polish theme toggle contrast": { title: "بهبود کنتراست تاگل تم تاریک" },
  "Shrink home resource cards": { title: "کوچک کردن کارت‌های ریسورس صفحه اصلی" },
  "Add pagination examples": { title: "افزودن مثال‌های صفحه‌بندی فارسی" },
  "Draft workshop notes": { title: "پیش‌نویس یادداشت‌های کارگاه تهران" },
  "Index posts.user_id": { title: "ایندکس posts.user_id در دیتابیس" },
  "Persist playground token": { title: "پایدار کردن توکن پلی‌گراند" },
  "Tune search ilike patterns": { title: "تنظیم الگوهای جستجوی ilike" },
  "Rewrite sample post copy": { title: "بازنویسی متن نمونه پست‌ها به فارسی طبیعی" },
  "Document rate-limit headers": { title: "مستندسازی هدرهای محدودیت نرخ" },
  "Sync OpenAPI on every PR": { title: "همگام‌سازی OpenAPI در هر PR" },
  "Publish travel draft": { title: "انتشار پیش‌نویس سفر شمال" },
  "Profile wall by userId": { title: "دیوار پروفایل با فیلتر userId" },
  "Fix seed delete order": { title: "درست کردن ترتیب حذف seed" },
  "Boolean query parse tip": { title: "نکته پارس کوئری بولین" },
  "Unify error payload shape": { title: "یکدست کردن شکل پیلود خطا" },
  "Cap delay at 5000ms": { title: "سقف delay روی ۵۰۰۰ میلی‌ثانیه" },
  "Limit tags to 20": { title: "محدود کردن تگ‌ها به ۲۰" },
  "Add title sort option": { title: "افزودن گزینه مرتب‌سازی عنوان" },
  "Verify Resend domain": { title: "تأیید دامنه ارسال ایمیل" },
  "Show curl in docs panel": { title: "نمایش curl در پنل مستندات" },
  "Keep UUID primary keys": { title: "حفظ کلید اصلی UUID" },
  "Welcome new installs": { title: "خوش‌آمد به نصب‌های جدید" },
};
