export type FaUserOverlay = {
  name: string;
  username: string;
  email: string;
  phone: string;
  company: string;
  city: string;
  country: string;
  bio: string;
  website: string | null;
  avatarUrl?: string;
};

/** Keyed by English seed username. */
export const faUsers: Record<string, FaUserOverlay> = {
  avachen: {
    name: "سارا محمدی",
    username: "sara.mohammadi",
    email: "sara.mohammadi@example.ir",
    phone: "+98 912 345 0101",
    company: "نوآوران داده",
    city: "تهران",
    country: "ایران",
    bio: "مهندس محصول؛ روی ابزارهای توسعه‌دهنده و داشبورد API کار می‌کند.",
    website: "https://example.ir/sara",
    avatarUrl: "https://i.pravatar.cc/150?u=sara.mohammadi",
  },
  mreid: {
    name: "رضا کریمی",
    username: "reza.karimi",
    email: "reza.karimi@example.ir",
    phone: "+98 913 220 4488",
    company: "پارس‌تک",
    city: "اصفهان",
    country: "ایران",
    bio: "لید فرانت‌اند؛ سیستم طراحی و کامپوننت‌های ری‌اکت می‌سازد.",
    website: "https://example.ir/reza",
    avatarUrl: "https://i.pravatar.cc/150?u=reza.karimi",
  },
  "sofia.a": {
    name: "نیلوفر احمدی",
    username: "niloufar.ahmadi",
    email: "niloufar.ahmadi@example.ir",
    phone: "+98 917 555 3322",
    company: "ابرآسا",
    city: "شیراز",
    country: "ایران",
    bio: "توسعه‌دهنده فول‌استک و نگهدارنده پروژه‌های متن‌باز فارسی.",
    website: null,
    avatarUrl: "https://i.pravatar.cc/150?u=niloufar.ahmadi",
  },
  noahk: {
    name: "کیان رضایی",
    username: "kian.rezaei",
    email: "kian.rezaei@example.ir",
    phone: "+98 915 666 7788",
    company: "سپهر دیجیتال",
    city: "مشهد",
    country: "ایران",
    bio: "در حال کشف APIها و ساخت پروژه‌های جانبی با نکست.",
    website: "https://example.ir/kian",
    avatarUrl: "https://i.pravatar.cc/150?u=kian.rezaei",
  },
  epetrova: {
    name: "مریم حسینی",
    username: "maryam.hosseini",
    email: "maryam.hosseini@example.ir",
    phone: "+98 914 111 2299",
    company: "دیتانیکس",
    city: "تبریز",
    country: "ایران",
    bio: "مهندس بک‌اند با تخصص در Postgres و اسکیماهای تمیز.",
    website: null,
    avatarUrl: "https://i.pravatar.cc/150?u=maryam.hosseini",
  },
  jwright: {
    name: "امیر حسینی",
    username: "amir.hosseini",
    email: "amir.hosseini@example.ir",
    phone: "+98 912 888 0011",
    company: "فناوران آریا",
    city: "کرج",
    country: "ایران",
    bio: "مدیر مهندسی تیم‌های پلتفرم و زیرساخت.",
    website: "https://example.ir/amir",
    avatarUrl: "https://i.pravatar.cc/150?u=amir.hosseini",
  },
  priyan: {
    name: "زهرا نوری",
    username: "zahra.nouri",
    email: "zahra.nouri@example.ir",
    phone: "+98 916 444 5566",
    company: "موبایل‌ویژن",
    city: "اهواز",
    country: "ایران",
    bio: "مهندس موبایل؛ اپ‌های React Native برای بازار ایران می‌سازد.",
    website: "https://example.ir/zahra",
    avatarUrl: "https://i.pravatar.cc/150?u=zahra.nouri",
  },
  lmoreau: {
    name: "پارسا مرادی",
    username: "parsa.moradi",
    email: "parsa.moradi@example.ir",
    phone: "+98 913 777 8899",
    company: "آتلیه کد پارس",
    city: "یزد",
    country: "ایران",
    bio: "مهندس UX؛ پل بین طراحی و کد فرانت‌اند.",
    website: null,
    avatarUrl: "https://i.pravatar.cc/150?u=parsa.moradi",
  },
  hbrooks: {
    name: "هانیه برومند",
    username: "hanie.boroumand",
    email: "hanie.boroumand@example.ir",
    phone: "+98 912 333 4455",
    company: "آزمایشگاه کیفیت",
    city: "تهران",
    country: "ایران",
    bio: "متخصص QA؛ تست قرارداد API و سناریوهای UI می‌نویسد.",
    website: "https://example.ir/hanie",
    avatarUrl: "https://i.pravatar.cc/150?u=hanie.boroumand",
  },
  ohassan: {
    name: "علی حسنی",
    username: "ali.hasani",
    email: "ali.hasani@example.ir",
    phone: "+98 911 222 3344",
    company: "ابرپارس",
    city: "رشت",
    country: "ایران",
    bio: "معمار ابری برای سرویس‌های چندمنطقه‌ای و CDN.",
    website: "https://example.ir/ali",
    avatarUrl: "https://i.pravatar.cc/150?u=ali.hasani",
  },
  ytanaka: {
    name: "یاسمن کاظمی",
    username: "yasaman.kazemi",
    email: "yasaman.kazemi@example.ir",
    phone: "+98 912 555 6677",
    company: "تایپ‌نود",
    city: "قم",
    country: "ایران",
    bio: "علاقه‌مند به TypeScript و سخنران میت‌آپ‌های فرانت‌اند تهران.",
    website: null,
    avatarUrl: "https://i.pravatar.cc/150?u=yasaman.kazemi",
  },
  icosta: {
    name: "آزاده قربانی",
    username: "azadeh.ghorbani",
    email: "azadeh.ghorbani@example.ir",
    phone: "+98 913 999 0012",
    company: "استارتاپ‌هاب",
    city: "کرمان",
    country: "ایران",
    bio: "CTO؛ منتور تیم‌های نوپا در اکوسیستم استارتاپی ایران.",
    website: "https://example.ir/azadeh",
    avatarUrl: "https://i.pravatar.cc/150?u=azadeh.ghorbani",
  },
  dokonkwo: {
    name: "دانیال اکبری",
    username: "danial.akbari",
    email: "danial.akbari@example.ir",
    phone: "+98 918 111 2233",
    company: "پرداخت‌یار",
    city: "همدان",
    country: "ایران",
    bio: "ساخت API پرداخت و درگاه برای فروشگاه‌های آنلاین.",
    website: "https://example.ir/danial",
    avatarUrl: "https://i.pravatar.cc/150?u=danial.akbari",
  },
  mjohansson: {
    name: "مینا جوادی",
    username: "mina.javadi",
    email: "mina.javadi@example.ir",
    phone: "+98 914 555 7788",
    company: "بیت‌استودیو",
    city: "ارومیه",
    country: "ایران",
    bio: "طراح محصول در حال یادگیری مصرف REST API.",
    website: null,
    avatarUrl: "https://i.pravatar.cc/150?u=mina.javadi",
  },
  eclarke: {
    name: "احسان کلامی",
    username: "ehsan.kalami",
    email: "ehsan.kalami@example.ir",
    phone: "+98 912 666 8899",
    company: "داده‌کاو",
    city: "تهران",
    country: "ایران",
    bio: "مهندس داده؛ عاشق اسکیماهای تمیز و پایپ‌لاین ETL.",
    website: "https://example.ir/ehsan",
    avatarUrl: "https://i.pravatar.cc/150?u=ehsan.kalami",
  },
  asaleh: {
    name: "امیره صالحی",
    username: "amireh.salehi",
    email: "amireh.salehi@example.ir",
    phone: "+98 917 222 3344",
    company: "امن‌نت",
    city: "بوشهر",
    country: "ایران",
    bio: "مهندس امنیت؛ بررسی جریان‌های احراز هویت و OAuth.",
    website: null,
    avatarUrl: "https://i.pravatar.cc/150?u=amireh.salehi",
  },
  tsilva: {
    name: "توماج سلیمانی",
    username: "tomaj.soleimani",
    email: "tomaj.soleimani@example.ir",
    phone: "+98 911 444 5566",
    company: "کدآتلانتیک",
    city: "ساری",
    country: "ایران",
    bio: "فریلنسر؛ نمونه‌سازی اپ‌های مشتری با نکست و ری‌اکت.",
    website: "https://example.ir/tomaj",
    avatarUrl: "https://i.pravatar.cc/150?u=tomaj.soleimani",
  },
  gliu: {
    name: "گلناز لیلایی",
    username: "golnaz.leilaei",
    email: "golnaz.leilaei@example.ir",
    phone: "+98 912 777 9900",
    company: "هاربر استک پارس",
    city: "زنجان",
    country: "ایران",
    bio: "مهندس پلتفرم؛ خودکارسازی دیپلوی و CI/CD.",
    website: "https://example.ir/golnaz",
    avatarUrl: "https://i.pravatar.cc/150?u=golnaz.leilaei",
  },
  bortiz: {
    name: "بهنام اورتی",
    username: "behnam.ortizi",
    email: "behnam.ortizi@example.ir",
    phone: "+98 914 333 2211",
    company: "اپ‌سازان",
    city: "اردبیل",
    country: "ایران",
    bio: "توسعه‌دهنده موبایل؛ اتصال کلاینت به بک‌اندهای ماک.",
    website: null,
    avatarUrl: "https://i.pravatar.cc/150?u=behnam.ortizi",
  },
  cmartin: {
    name: "کیانا مرتضوی",
    username: "kiana.mortazavi",
    email: "kiana.mortazavi@example.ir",
    phone: "+98 912 101 2020",
    company: "فین‌تک البرز",
    city: "قزوین",
    country: "ایران",
    bio: "رئیس مهندسی محصولات فین‌تک و کیف پول دیجیتال.",
    website: "https://example.ir/kiana",
    avatarUrl: "https://i.pravatar.cc/150?u=kiana.mortazavi",
  },
  rpatel: {
    name: "رامین پناهی",
    username: "ramin.panahi",
    email: "ramin.panahi@example.ir",
    phone: "+98 917 303 4040",
    company: "کلادمیانه",
    city: "شیراز",
    country: "ایران",
    bio: "مهندس DevOps؛ نوشتن ماژول‌های Terraform و مانیتورینگ.",
    website: "https://example.ir/ramin",
    avatarUrl: "https://i.pravatar.cc/150?u=ramin.panahi",
  },
  nvolkov: {
    name: "نگار ولایتی",
    username: "negar.velayati",
    email: "negar.velayati@example.ir",
    phone: "+98 913 505 6060",
    company: "مدار استودیو",
    city: "اصفهان",
    country: "ایران",
    bio: "دانشجو؛ دموهای پورتفولیو با API ساختگی می‌سازد.",
    website: null,
    avatarUrl: "https://i.pravatar.cc/150?u=negar.velayati",
  },
  landersson: {
    name: "لیلا اندرزگو",
    username: "leila.andarzgoo",
    email: "leila.andarzgoo@example.ir",
    phone: "+98 917 707 8080",
    company: "آپ‌تایم پارس",
    city: "بندرعباس",
    country: "ایران",
    bio: "SRE؛ نمودارهای آپ‌تایم را ساده و قابل اعتماد نگه می‌دارد.",
    website: "https://example.ir/leila",
    avatarUrl: "https://i.pravatar.cc/150?u=leila.andarzgoo",
  },
  fzahra: {
    name: "فاطمه رضایی",
    username: "fateme.rezaei",
    email: "fateme.rezaei@example.ir",
    phone: "+98 913 909 1010",
    company: "طراحی اطلس",
    city: "کاشان",
    country: "ایران",
    bio: "طراح محصول؛ همکاری نزدیک با مهندسان فرانت‌اند.",
    website: "https://example.ir/fateme",
    avatarUrl: "https://i.pravatar.cc/150?u=fateme.rezaei",
  },
};
