import type { NewProduct } from "./schema/products";

export const seedProducts: Omit<NewProduct, "id" | "createdAt" | "updatedAt">[] =
  [
    {
      name: "Nordic Desk Lamp",
      description: "Matte aluminum lamp with warm dimmable LED.",
      price: 49.99,
      stock: 120,
      category: "home",
      imageUrl: "https://picsum.photos/seed/lamp/600/400",
    },
    {
      name: "Ceramic Pour-Over Set",
      description: "Two-cup pour-over with matching mug.",
      price: 34.5,
      stock: 80,
      category: "kitchen",
      imageUrl: "https://picsum.photos/seed/coffee/600/400",
    },
    {
      name: "Canvas Weekender",
      description: "Water-resistant canvas bag with leather straps.",
      price: 89,
      stock: 45,
      category: "travel",
      imageUrl: "https://picsum.photos/seed/bag/600/400",
    },
    {
      name: "Mechanical Keyboard",
      description: "Hot-swap 75% board with silent switches.",
      price: 129.99,
      stock: 60,
      category: "electronics",
      imageUrl: "https://picsum.photos/seed/keyboard/600/400",
    },
    {
      name: "Wool Throw Blanket",
      description: "Soft merino blend in charcoal stripe.",
      price: 72,
      stock: 95,
      category: "home",
      imageUrl: "https://picsum.photos/seed/blanket/600/400",
    },
    {
      name: "Trail Running Shoes",
      description: "Grip sole and breathable mesh upper.",
      price: 118,
      stock: 70,
      category: "sports",
      imageUrl: "https://picsum.photos/seed/shoes/600/400",
    },
    {
      name: "Noise-Cancel Headphones",
      description: "Over-ear ANC with 30-hour battery.",
      price: 199.99,
      stock: 40,
      category: "electronics",
      imageUrl: "https://picsum.photos/seed/headphones/600/400",
    },
    {
      name: "Cast Iron Skillet",
      description: "Pre-seasoned 10-inch skillet.",
      price: 54,
      stock: 110,
      category: "kitchen",
      imageUrl: "https://picsum.photos/seed/skillet/600/400",
    },
    {
      name: "Linen Sheet Set",
      description: "Stonewashed linen, queen size.",
      price: 148,
      stock: 55,
      category: "home",
      imageUrl: "https://picsum.photos/seed/sheets/600/400",
    },
    {
      name: "Portable SSD 1TB",
      description: "USB-C drive with 1050 MB/s read.",
      price: 109,
      stock: 200,
      category: "electronics",
      imageUrl: "https://picsum.photos/seed/ssd/600/400",
    },
    {
      name: "Climbing Chalk Bag",
      description: "Compact chalk bag with brush loop.",
      price: 24.99,
      stock: 150,
      category: "sports",
      imageUrl: "https://picsum.photos/seed/chalk/600/400",
    },
    {
      name: "Glass Water Bottle",
      description: "500ml borosilicate with silicone sleeve.",
      price: 22,
      stock: 180,
      category: "travel",
      imageUrl: "https://picsum.photos/seed/bottle/600/400",
    },
    {
      name: "Desk Plant Stand",
      description: "Oak riser for small pots.",
      price: 28.5,
      stock: 90,
      category: "home",
      imageUrl: "https://picsum.photos/seed/plant/600/400",
    },
    {
      name: "Chef Knife 8 inch",
      description: "High-carbon steel with walnut handle.",
      price: 96,
      stock: 65,
      category: "kitchen",
      imageUrl: "https://picsum.photos/seed/knife/600/400",
    },
    {
      name: "USB-C Hub",
      description: "7-in-1 hub with HDMI and SD card slot.",
      price: 59.99,
      stock: 130,
      category: "electronics",
      imageUrl: "https://picsum.photos/seed/hub/600/400",
    },
    {
      name: "Yoga Mat",
      description: "Non-slip 5mm mat with carry strap.",
      price: 39,
      stock: 140,
      category: "sports",
      imageUrl: "https://picsum.photos/seed/yoga/600/400",
    },
    {
      name: "Travel Adapter",
      description: "Universal adapter with dual USB-C PD.",
      price: 32,
      stock: 175,
      category: "travel",
      imageUrl: "https://picsum.photos/seed/adapter/600/400",
    },
    {
      name: "Scented Candle",
      description: "Cedar and bergamot soy wax, 40-hour burn.",
      price: 26,
      stock: 210,
      category: "home",
      imageUrl: "https://picsum.photos/seed/candle/600/400",
    },
    {
      name: "Espresso Tamper",
      description: "58mm calibrated spring tamper.",
      price: 44,
      stock: 75,
      category: "kitchen",
      imageUrl: "https://picsum.photos/seed/tamper/600/400",
    },
    {
      name: "Wireless Mouse",
      description: "Quiet click mouse with multi-device pairing.",
      price: 42.5,
      stock: 160,
      category: "electronics",
      imageUrl: "https://picsum.photos/seed/mouse/600/400",
    },
    {
      name: "Resistance Bands Set",
      description: "Five bands with door anchor and bag.",
      price: 29.99,
      stock: 190,
      category: "sports",
      imageUrl: "https://picsum.photos/seed/bands/600/400",
    },
    {
      name: "Packable Rain Jacket",
      description: "Lightweight shell that packs into its pocket.",
      price: 78,
      stock: 85,
      category: "travel",
      imageUrl: "https://picsum.photos/seed/jacket/600/400",
    },
    {
      name: "Monitor Light Bar",
      description: "Screen-mounted light with auto-dim.",
      price: 69,
      stock: 100,
      category: "electronics",
      imageUrl: "https://picsum.photos/seed/lightbar/600/400",
    },
    {
      name: "Herb Garden Kit",
      description: "Basil, mint, and parsley starter pots.",
      price: 31,
      stock: 120,
      category: "home",
      imageUrl: "https://picsum.photos/seed/herbs/600/400",
    },
  ];
