import type { NewUser } from "./schema/users";

type SeedUser = Omit<NewUser, "id" | "createdAt" | "updatedAt">;

export const seedUsers: SeedUser[] = [
  {
    name: "Ava Chen",
    username: "avachen",
    email: "ava.chen@example.com",
    avatarUrl: "https://i.pravatar.cc/150?u=avachen",
    phone: "+1 415 555 0142",
    company: "Northwind Labs",
    role: "admin",
    city: "San Francisco",
    country: "United States",
    bio: "Product engineer focused on developer tooling.",
    website: "https://example.com/ava",
  },
  {
    name: "Marcus Reid",
    username: "mreid",
    email: "marcus.reid@example.com",
    avatarUrl: "https://i.pravatar.cc/150?u=mreid",
    phone: "+44 20 7946 0958",
    company: "Brightline",
    role: "member",
    city: "London",
    country: "United Kingdom",
    bio: "Frontend lead building design systems.",
    website: "https://example.com/marcus",
  },
  {
    name: "Sofia Alvarez",
    username: "sofia.a",
    email: "sofia.alvarez@example.com",
    avatarUrl: "https://i.pravatar.cc/150?u=sofia",
    phone: "+34 91 123 4567",
    company: "Iberia Soft",
    role: "member",
    city: "Madrid",
    country: "Spain",
    bio: "Full-stack developer and open-source maintainer.",
    website: null,
  },
  {
    name: "Noah Kim",
    username: "noahk",
    email: "noah.kim@example.com",
    avatarUrl: "https://i.pravatar.cc/150?u=noahk",
    phone: "+82 2 555 0199",
    company: "Han River Digital",
    role: "guest",
    city: "Seoul",
    country: "South Korea",
    bio: "Exploring APIs and side projects.",
    website: "https://example.com/noah",
  },
  {
    name: "Elena Petrova",
    username: "epetrova",
    email: "elena.petrova@example.com",
    avatarUrl: "https://i.pravatar.cc/150?u=elena",
    phone: "+49 30 555 2211",
    company: "Berlin Circuits",
    role: "member",
    city: "Berlin",
    country: "Germany",
    bio: "Backend engineer specializing in Postgres.",
    website: null,
  },
  {
    name: "Jamal Wright",
    username: "jwright",
    email: "jamal.wright@example.com",
    avatarUrl: "https://i.pravatar.cc/150?u=jamal",
    phone: "+1 646 555 0188",
    company: "Harbor Apps",
    role: "admin",
    city: "New York",
    country: "United States",
    bio: "Engineering manager for platform teams.",
    website: "https://example.com/jamal",
  },
  {
    name: "Priya Nair",
    username: "priyan",
    email: "priya.nair@example.com",
    avatarUrl: "https://i.pravatar.cc/150?u=priya",
    phone: "+91 22 5555 3344",
    company: "Monsoon Tech",
    role: "member",
    city: "Mumbai",
    country: "India",
    bio: "Mobile engineer shipping React Native apps.",
    website: "https://example.com/priya",
  },
  {
    name: "Lucas Moreau",
    username: "lmoreau",
    email: "lucas.moreau@example.com",
    avatarUrl: "https://i.pravatar.cc/150?u=lucas",
    phone: "+33 1 42 68 5300",
    company: "Atelier Code",
    role: "member",
    city: "Paris",
    country: "France",
    bio: "UX engineer bridging design and code.",
    website: null,
  },
  {
    name: "Hannah Brooks",
    username: "hbrooks",
    email: "hannah.brooks@example.com",
    avatarUrl: "https://i.pravatar.cc/150?u=hannah",
    phone: "+61 2 5550 1122",
    company: "Coral Systems",
    role: "guest",
    city: "Sydney",
    country: "Australia",
    bio: "QA specialist writing API contract tests.",
    website: "https://example.com/hannah",
  },
  {
    name: "Omar Hassan",
    username: "ohassan",
    email: "omar.hassan@example.com",
    avatarUrl: "https://i.pravatar.cc/150?u=omar",
    phone: "+971 4 555 7788",
    company: "Dune Cloud",
    role: "member",
    city: "Dubai",
    country: "United Arab Emirates",
    bio: "Cloud architect for multi-region services.",
    website: "https://example.com/omar",
  },
  {
    name: "Yuki Tanaka",
    username: "ytanaka",
    email: "yuki.tanaka@example.com",
    avatarUrl: "https://i.pravatar.cc/150?u=yuki",
    phone: "+81 3 5555 0909",
    company: "Tokyo Node",
    role: "member",
    city: "Tokyo",
    country: "Japan",
    bio: "TypeScript enthusiast and conference speaker.",
    website: null,
  },
  {
    name: "Isabella Costa",
    username: "icosta",
    email: "isabella.costa@example.com",
    avatarUrl: "https://i.pravatar.cc/150?u=isabella",
    phone: "+55 11 5555 6677",
    company: "Selva Software",
    role: "admin",
    city: "São Paulo",
    country: "Brazil",
    bio: "CTO mentoring early-stage startups.",
    website: "https://example.com/isabella",
  },
  {
    name: "Daniel Okonkwo",
    username: "dokonkwo",
    email: "daniel.okonkwo@example.com",
    avatarUrl: "https://i.pravatar.cc/150?u=daniel",
    phone: "+234 1 555 4321",
    company: "Lagos Works",
    role: "member",
    city: "Lagos",
    country: "Nigeria",
    bio: "Building payment APIs for African markets.",
    website: "https://example.com/daniel",
  },
  {
    name: "Mia Johansson",
    username: "mjohansson",
    email: "mia.johansson@example.com",
    avatarUrl: "https://i.pravatar.cc/150?u=mia",
    phone: "+46 8 555 9911",
    company: "Nordic Bits",
    role: "guest",
    city: "Stockholm",
    country: "Sweden",
    bio: "Designer learning to consume REST APIs.",
    website: null,
  },
  {
    name: "Ethan Clarke",
    username: "eclarke",
    email: "ethan.clarke@example.com",
    avatarUrl: "https://i.pravatar.cc/150?u=ethan",
    phone: "+1 604 555 0155",
    company: "Cascade Data",
    role: "member",
    city: "Vancouver",
    country: "Canada",
    bio: "Data engineer with a love for clean schemas.",
    website: "https://example.com/ethan",
  },
  {
    name: "Amira Saleh",
    username: "asaleh",
    email: "amira.saleh@example.com",
    avatarUrl: "https://i.pravatar.cc/150?u=amira",
    phone: "+20 2 555 8844",
    company: "Nile Labs",
    role: "member",
    city: "Cairo",
    country: "Egypt",
    bio: "Security engineer reviewing auth flows.",
    website: null,
  },
  {
    name: "Tomás Silva",
    username: "tsilva",
    email: "tomas.silva@example.com",
    avatarUrl: "https://i.pravatar.cc/150?u=tomas",
    phone: "+351 21 555 3030",
    company: "Atlantic Code",
    role: "guest",
    city: "Lisbon",
    country: "Portugal",
    bio: "Freelance developer prototyping client apps.",
    website: "https://example.com/tomas",
  },
  {
    name: "Grace Liu",
    username: "gliu",
    email: "grace.liu@example.com",
    avatarUrl: "https://i.pravatar.cc/150?u=grace",
    phone: "+65 6555 1212",
    company: "Harbor Stack",
    role: "member",
    city: "Singapore",
    country: "Singapore",
    bio: "Platform engineer automating deployments.",
    website: "https://example.com/grace",
  },
  {
    name: "Benjamin Ortiz",
    username: "bortiz",
    email: "benjamin.ortiz@example.com",
    avatarUrl: "https://i.pravatar.cc/150?u=benjamin",
    phone: "+52 55 5555 7788",
    company: "Aztec Apps",
    role: "member",
    city: "Mexico City",
    country: "Mexico",
    bio: "iOS developer integrating mock backends.",
    website: null,
  },
  {
    name: "Chloe Martin",
    username: "cmartin",
    email: "chloe.martin@example.com",
    avatarUrl: "https://i.pravatar.cc/150?u=chloe",
    phone: "+41 22 555 6677",
    company: "Alpine Soft",
    role: "admin",
    city: "Geneva",
    country: "Switzerland",
    bio: "Head of engineering for fintech products.",
    website: "https://example.com/chloe",
  },
  {
    name: "Ryan Patel",
    username: "rpatel",
    email: "ryan.patel@example.com",
    avatarUrl: "https://i.pravatar.cc/150?u=ryan",
    phone: "+1 312 555 0190",
    company: "Midwest Cloud",
    role: "member",
    city: "Chicago",
    country: "United States",
    bio: "DevOps engineer writing Terraform modules.",
    website: "https://example.com/ryan",
  },
  {
    name: "Nina Volkov",
    username: "nvolkov",
    email: "nina.volkov@example.com",
    avatarUrl: "https://i.pravatar.cc/150?u=nina",
    phone: "+7 495 555 4411",
    company: "Orbit Studio",
    role: "guest",
    city: "Moscow",
    country: "Russia",
    bio: "Student building portfolio demos with mock APIs.",
    website: null,
  },
  {
    name: "Leo Andersson",
    username: "landersson",
    email: "leo.andersson@example.com",
    avatarUrl: "https://i.pravatar.cc/150?u=leo",
    phone: "+47 21 555 8899",
    company: "Fjord Digital",
    role: "member",
    city: "Oslo",
    country: "Norway",
    bio: "SRE keeping uptime charts boring.",
    website: "https://example.com/leo",
  },
  {
    name: "Fatima Zahra",
    username: "fzahra",
    email: "fatima.zahra@example.com",
    avatarUrl: "https://i.pravatar.cc/150?u=fatima",
    phone: "+212 5 555 2233",
    company: "Atlas Apps",
    role: "member",
    city: "Casablanca",
    country: "Morocco",
    bio: "Product designer collaborating with engineers.",
    website: "https://example.com/fatima",
  },
];
