import type { NewCountry } from "./schema/countries";

export const seedCountries: Omit<
  NewCountry,
  "id" | "createdAt" | "updatedAt"
>[] = [
  {
    name: "United States",
    code: "US",
    capital: "Washington, D.C.",
    region: "Americas",
    population: 331002651,
    currency: "USD",
    flagUrl: "https://flagcdn.com/w320/us.png",
  },
  {
    name: "Canada",
    code: "CA",
    capital: "Ottawa",
    region: "Americas",
    population: 37742154,
    currency: "CAD",
    flagUrl: "https://flagcdn.com/w320/ca.png",
  },
  {
    name: "United Kingdom",
    code: "GB",
    capital: "London",
    region: "Europe",
    population: 67886011,
    currency: "GBP",
    flagUrl: "https://flagcdn.com/w320/gb.png",
  },
  {
    name: "Germany",
    code: "DE",
    capital: "Berlin",
    region: "Europe",
    population: 83783942,
    currency: "EUR",
    flagUrl: "https://flagcdn.com/w320/de.png",
  },
  {
    name: "France",
    code: "FR",
    capital: "Paris",
    region: "Europe",
    population: 65273511,
    currency: "EUR",
    flagUrl: "https://flagcdn.com/w320/fr.png",
  },
  {
    name: "Italy",
    code: "IT",
    capital: "Rome",
    region: "Europe",
    population: 60461826,
    currency: "EUR",
    flagUrl: "https://flagcdn.com/w320/it.png",
  },
  {
    name: "Spain",
    code: "ES",
    capital: "Madrid",
    region: "Europe",
    population: 46754778,
    currency: "EUR",
    flagUrl: "https://flagcdn.com/w320/es.png",
  },
  {
    name: "Sweden",
    code: "SE",
    capital: "Stockholm",
    region: "Europe",
    population: 10099265,
    currency: "SEK",
    flagUrl: "https://flagcdn.com/w320/se.png",
  },
  {
    name: "Iran",
    code: "IR",
    capital: "Tehran",
    region: "Asia",
    population: 83992949,
    currency: "IRR",
    flagUrl: "https://flagcdn.com/w320/ir.png",
  },
  {
    name: "Japan",
    code: "JP",
    capital: "Tokyo",
    region: "Asia",
    population: 126476461,
    currency: "JPY",
    flagUrl: "https://flagcdn.com/w320/jp.png",
  },
  {
    name: "South Korea",
    code: "KR",
    capital: "Seoul",
    region: "Asia",
    population: 51269185,
    currency: "KRW",
    flagUrl: "https://flagcdn.com/w320/kr.png",
  },
  {
    name: "India",
    code: "IN",
    capital: "New Delhi",
    region: "Asia",
    population: 1380004385,
    currency: "INR",
    flagUrl: "https://flagcdn.com/w320/in.png",
  },
  {
    name: "China",
    code: "CN",
    capital: "Beijing",
    region: "Asia",
    population: 1439323776,
    currency: "CNY",
    flagUrl: "https://flagcdn.com/w320/cn.png",
  },
  {
    name: "Australia",
    code: "AU",
    capital: "Canberra",
    region: "Oceania",
    population: 25499884,
    currency: "AUD",
    flagUrl: "https://flagcdn.com/w320/au.png",
  },
  {
    name: "New Zealand",
    code: "NZ",
    capital: "Wellington",
    region: "Oceania",
    population: 4822233,
    currency: "NZD",
    flagUrl: "https://flagcdn.com/w320/nz.png",
  },
  {
    name: "Brazil",
    code: "BR",
    capital: "Brasília",
    region: "Americas",
    population: 212559417,
    currency: "BRL",
    flagUrl: "https://flagcdn.com/w320/br.png",
  },
  {
    name: "Mexico",
    code: "MX",
    capital: "Mexico City",
    region: "Americas",
    population: 128932753,
    currency: "MXN",
    flagUrl: "https://flagcdn.com/w320/mx.png",
  },
  {
    name: "Argentina",
    code: "AR",
    capital: "Buenos Aires",
    region: "Americas",
    population: 45195774,
    currency: "ARS",
    flagUrl: "https://flagcdn.com/w320/ar.png",
  },
  {
    name: "Egypt",
    code: "EG",
    capital: "Cairo",
    region: "Africa",
    population: 102334404,
    currency: "EGP",
    flagUrl: "https://flagcdn.com/w320/eg.png",
  },
  {
    name: "Nigeria",
    code: "NG",
    capital: "Abuja",
    region: "Africa",
    population: 206139589,
    currency: "NGN",
    flagUrl: "https://flagcdn.com/w320/ng.png",
  },
  {
    name: "South Africa",
    code: "ZA",
    capital: "Pretoria",
    region: "Africa",
    population: 59308690,
    currency: "ZAR",
    flagUrl: "https://flagcdn.com/w320/za.png",
  },
  {
    name: "Turkey",
    code: "TR",
    capital: "Ankara",
    region: "Asia",
    population: 84339067,
    currency: "TRY",
    flagUrl: "https://flagcdn.com/w320/tr.png",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    capital: "Abu Dhabi",
    region: "Asia",
    population: 9890402,
    currency: "AED",
    flagUrl: "https://flagcdn.com/w320/ae.png",
  },
  {
    name: "Singapore",
    code: "SG",
    capital: "Singapore",
    region: "Asia",
    population: 5850342,
    currency: "SGD",
    flagUrl: "https://flagcdn.com/w320/sg.png",
  },
];
